image: Visual Studio 2017
configuration: Release
version: '1.0.{build}'

dotnet_csproj:
    patch: true
    file: src/GarfSG.GetProxyListClient/GarfSG.GetProxyListClient.csproj
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
    
before_build:
- cmd: >-
    dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test_script:
  - cmd: dotnet test tests/GarfSG.GetProxyListClient.Tests/GarfSG.GetProxyListClient.Tests.csproj
  
